#Lab10
#server:
#  port: 8081
#zuul:
#  routes:
#    books.url: http://localhost:8090    #路由配置，省略path,直接取routeId为path

#Lab10 实验
server:
  port: 8083
zuul:
  routes:
    abc.url: http://localhost:8085
