#Lab10
spring:
  application:
    name: person-server
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka
server:
  port: 9001
