#Lab1
#spring:
#  application:
#    name: provider
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone:
#        http://localhost:8761/eureka

#Lab2
spring:
  application:
    name: provider
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/, http://localhost:8762/eureka/
