#Lab1
#spring:
#  application:
#    name: provider
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone:
#        http://localhost:8761/eureka

#Lab2-1
#spring:
#  application:
#    name: provider
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone:
#        http://localhost:8761/eureka/, http://localhost:8762/eureka/

#Lab2-2
#spring:
#  application:
#    name: provider
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone:
#        http://localhost:8761/eureka/
#    initial-instance-info-replication-interval-seconds: 10
#server:
#  port: 8083

#Lab4、lab6
spring:
  application:
    name: provider
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka
