#Lab10
#spring:
#  application:
#    name: zuulGateway
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#zuul:
#  routes:
#    sale:
#      path: /sale/**
#      serviceId: sale-service
#    helloRoute.path: /test/**
#    helloRoute.url: forward:/source
#server:
#  port: 8081

#Lab10 实验
spring:
  application:
    name: zuulGateway
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    book:
      path: /book/**
      serviceId: book-invoker
    person:
      path: /person/**
      serviceId: person-invoker
server:
  port: 8085
