my-client.ribbon.listOfServers: localhost:8081, localhost:8085
#my-client:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.sise.ribbonClient.Rule
#my-client:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
my-client:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.PingUrl
    NFLoadBalancerPingInterval: 2

