server:
  port: 8081
spring:
  application:
    name: rabbit-consumer
  rabbitmq:
    host: localhost
  cloud:
    stream:
      binders:
        myInput:
          group: groupA
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
