#server:
#  port: 9000
#spring:
#  application:
#    name: invoker
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#Lab4
#server:
#  port: 9000
#spring:
#  application:
#    name: invoker
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.sise.invoker.ribbon.Rule
#    NFLoadBalancerPingClassName: com.sise.invoker.ribbon.Ping
#    listOfServers: http://localhost:8081, http://localhost:8085

#Lab6
#多个接口上的@FeignClient(“相同服务名”)会报错，overriding is disabled。
#设置为true ,即允许同名
#spring:
# main:
#  allow-bean-definition-overriding: true
server:
  port: 9000
spring:
  application:
    name: invoker
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
