server:
  port: 8084
spring:
  application:
    name: second-rabbit-consumer
  rabbitmq:
    host: localhost
  cloud:
    stream:
      binders:
        myInput:
          group: groupB
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


