spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    staticPathPattern: /**
  resources:
    staticLocations: classpath:/META-INF/resource/,classpath:/resource/,classpath:/static/,classpath:/public/
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initalization-size: 10
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: dbService
server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
